### ISSUE TITLE
Add Meta Descriptions

### ISSUE THREAD

**Issue by john-l-hansen** [Peeas/brownco#17]
Meta Descriptions by Page

Title: Careers | Brownco
Description: It's not easy work but it is rewarding. We are growing and looking for hardworking team players with grit! Submit a resume at Brownco Construction Co. Inc.’s website.

Title: Concrete Construction | Brownco
Description: Brownco has the skill and the ability to “think outside the pit” when it comes to concrete machine foundations and press pits.

Title: About Us | Brownco
Description: Think Safety Work Safely, The Brownco Way. Building with Purpose.

Title: Home | Brownco 
Description: Every industrial commercial building needs Brownco Construction Co., Inc. someday they
will need refurbishment, repairs, additions and/or modifications.

Title: Contact | BrowncoBuilding
Description: Damage? No problem call Brownco Construction Company, Inc. for your emergency
construction needs.

Title: Structural Steel | Brownco
Description: Brownco Construction Company Inc. fabricated and installed employee protection guardrail. Need guardrails, safety bollards, ADA compliance? 

Title: Tenant Improvement | Brownco
Description: New offices, bathrooms, conference room - Call Brownco Construction Co Inc. for all your tenant improvements. Let's talk project!

Title: Demolition and Excavation | Brownco
Description: Brownco loves to tear buildings up, call today for your demolition and excavation proposal.

Title: Renewable Energy | Brownco 
Description: For over 20 years Brownco has been providing renewable energy solutions for clients. Wanna talk about it, we are green to consult with you today!

**Comment by richdurazo** [comment]
@john-l-hansen  this is doneeeee
