### ISSUE TITLE
Fix Page Location When Navigating

### ISSUE THREAD

**Issue by john-l-hansen** [Peeas/brownco#20]
Currently, if a User scrolls to the middle of a view, and then clicks out to another view, they are sent correctly but at the same location, they were on the previous view.

As it's fairly jarring for most, it'd be better if the User was sent to the top of the view selected, a more standard behavior.

**Comment by richdurazo** [comment]
@john-l-hansen this can be moved to done I believe

**Comment by richdurazo** [comment]
closing
