### ISSUE TITLE
CMS Functionality for New Projects

### ISSUE THREAD

**Issue by john-l-hansen** [Peeas/brownco#24]
**Client Request**
As a User, I want to be able to add portfolios of recent projects demonstrating recent work. I want to be able to do this with autonomy, without developer aid.

**Need**
- Ability to create new pages within the prescribed category (see navigation)

**Categories**
- Aerospace
- Commercial
- Education
- Energy
- Food Processing/Manufacturing
- Government
- Medical/Pharmaceutical
- Metal Industries
- Paper Manufacturing
- Unique

(There is an error in the navigation link, paper manufacturing is listed twice, please disregard).

**Considerations**
These are things I know inherently that may come up:

- Can we show only industries that content added?
- Can we make meta descriptions and tags of pages editable?

**Navigation**
https://invis.io/GBOE4ZN543K#/369250520_Navigation_-_Industries

**Page Template**
https://invis.io/GBOE4ZN543K#/369250519_Industries_-_Template

**Comment by richdurazo** [comment]
@john-l-hansen  this is complete with editable meta tags and descriptions.
